from fastapi import FastAPI, Request, UploadFile, Form
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel
import requests
import uuid
from typing import Dict, List, Optional
from threading import Lock

app = FastAPI()

# In-memory session storage
sessions: Dict[str, List[str]] = {}
sessions_lock = Lock()

OLLAMA_URL = "http://localhost:11434/api/generate"

# Declare Pydantic model for better input handling and verification
class GenerateRequest(BaseModel):
    prompt: str
    model: Optional[str] = "qwen3:4b"
    temperature: Optional[float] = 0.7
    top_p: Optional[float] = 0.9
    session_id: Optional[str] = None
    stream: Optional[bool] = False #TODO: Add functionality for streaming


@app.get("/")
async def root():
    return {"message": "Ollama FastAPI API with session management is running."}


@app.post("/generate")
async def generate(req: GenerateRequest):
    """

    :param req: User request containing prompt and optional variables like model, temperature, top_p, session_id, streaming_output\n
    :return: Text response generated by the LLM for the user query
    """
    session_id = req.session_id or str(uuid.uuid4())

    with sessions_lock:
        if session_id not in sessions:
            sessions[session_id] = []
        sessions[session_id].append(f"User: {req.prompt}")

    payload = {
        "model": req.model,
        "prompt": "\n".join(sessions[session_id]),
        "options": {
            "temperature": req.temperature,
            "top_p": req.top_p
        },
        "stream": req.stream
    }

    if req.stream:
        def event_stream():
            response = requests.post(OLLAMA_URL, json=payload, stream=True)
            for line in response.iter_lines():
                if line:
                    yield line.decode("utf-8") + "\n"

        return StreamingResponse(event_stream(), media_type="text/plain")

    else:
        response = requests.post(OLLAMA_URL, json=payload)
        result = response.json()

        with sessions_lock:
            sessions[session_id].append(f"AI: {result.get('response')}")

        return JSONResponse(content={"response": result.get("response"), "session_id": session_id})


@app.get("/session/{session_id}")
async def get_session_history(session_id: str):
    """

    :param session_id: The session id for which the user wants to see the history\n
    :return: JSON object containing the user's session history
    """
    with sessions_lock:
        history = sessions.get(session_id)
        if history is None:
            return JSONResponse(content={"error": "Session not found"}, status_code=404)
    return {"session_id": session_id, "history": history}


@app.delete("/session/{session_id}")
async def delete_session(session_id: str):
    """

    :param session_id: The session id that the user wants to delete\n
    :return: Acknowledgement if the session was deleted or not
    """
    with sessions_lock:
        if session_id in sessions:
            del sessions[session_id]
            return {"message": f"Session {session_id} deleted."}
        else:
            return JSONResponse(content={"error": "Session not found"}, status_code=404)


@app.post("/generate_image_query")
async def generate_image_query(
    image: UploadFile,
    prompt: str = Form(...),
    model: Optional[str] = Form("qwen-vl")
):
    """

    :param image: Input image the user wants to query on\n
    :param prompt: Prompt from the user\n
    :param model: The vision model the user wants to use\n
    :return: Text response to the user generated from the VLM\n
    """
    import base64

    image_bytes = await image.read()
    encoded_image = base64.b64encode(image_bytes).decode("utf-8")

    payload = {
        "model": model,
        "prompt": prompt,
        "images": [encoded_image],
        "stream": False
    }

    response = requests.post(OLLAMA_URL, json=payload)
    result = response.json()

    return JSONResponse(content={"response": result.get("response")})


# @app.post("/generate_from_pdf")
# async def generate_from_pdf(file: UploadFile):
#     # Extract text from PDF (using pdfplumber or PyMuPDF)
#     # Send extracted text to Ollama prompt
#     pass
